apiVersion: v1
kind: Service
metadata:
  name: mb-apiserver
  labels:
    app: mb-apiserver
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5555
      targetPort: 5555
    - name: grpc
      protocol: TCP
      port: 6666
      targetPort: 6666
  selector:
    app: mb-apiserver
  sessionAffinity: None
  type: ClusterIP
