// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: apiserver/v1/healthz.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServiceStatus 表示服务的健康状态
type ServiceStatus int32

const (
	// Healthy 表示服务健康
	ServiceStatus_Healthy ServiceStatus = 0
	// Unhealthy 表示服务不健康
	ServiceStatus_Unhealthy ServiceStatus = 1
)

// Enum value maps for ServiceStatus.
var (
	ServiceStatus_name = map[int32]string{
		0: "Healthy",
		1: "Unhealthy",
	}
	ServiceStatus_value = map[string]int32{
		"Healthy":   0,
		"Unhealthy": 1,
	}
)

func (x ServiceStatus) Enum() *ServiceStatus {
	p := new(ServiceStatus)
	*p = x
	return p
}

func (x ServiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_apiserver_v1_healthz_proto_enumTypes[0].Descriptor()
}

func (ServiceStatus) Type() protoreflect.EnumType {
	return &file_apiserver_v1_healthz_proto_enumTypes[0]
}

func (x ServiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceStatus.Descriptor instead.
func (ServiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_apiserver_v1_healthz_proto_rawDescGZIP(), []int{0}
}

// HealthzResponse 表示健康检查的响应结构体
type HealthzResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// status 表示服务的健康状态
	Status ServiceStatus `protobuf:"varint,1,opt,name=status,proto3,enum=v1.ServiceStatus" json:"status,omitempty"`
	// timestamp 表示请求的时间戳
	Timestamp string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// message 表示可选的状态消息，描述服务健康的更多信息
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HealthzResponse) Reset() {
	*x = HealthzResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apiserver_v1_healthz_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzResponse) ProtoMessage() {}

func (x *HealthzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_healthz_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzResponse.ProtoReflect.Descriptor instead.
func (*HealthzResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_healthz_proto_rawDescGZIP(), []int{0}
}

func (x *HealthzResponse) GetStatus() ServiceStatus {
	if x != nil {
		return x.Status
	}
	return ServiceStatus_Healthy
}

func (x *HealthzResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *HealthzResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_apiserver_v1_healthz_proto protoreflect.FileDescriptor

var file_apiserver_v1_healthz_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x68,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x7a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31,
	0x22, 0x74, 0x0a, 0x0f, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x2b, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x79, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x6e, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x79, 0x10, 0x01, 0x42, 0x22, 0x5a, 0x20, 0x6d, 0x69, 0x6e, 0x69, 0x62, 0x6c, 0x6f, 0x67, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apiserver_v1_healthz_proto_rawDescOnce sync.Once
	file_apiserver_v1_healthz_proto_rawDescData = file_apiserver_v1_healthz_proto_rawDesc
)

func file_apiserver_v1_healthz_proto_rawDescGZIP() []byte {
	file_apiserver_v1_healthz_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_healthz_proto_rawDescData = protoimpl.X.CompressGZIP(file_apiserver_v1_healthz_proto_rawDescData)
	})
	return file_apiserver_v1_healthz_proto_rawDescData
}

var file_apiserver_v1_healthz_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_apiserver_v1_healthz_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_apiserver_v1_healthz_proto_goTypes = []any{
	(ServiceStatus)(0),      // 0: v1.ServiceStatus
	(*HealthzResponse)(nil), // 1: v1.HealthzResponse
}
var file_apiserver_v1_healthz_proto_depIdxs = []int32{
	0, // 0: v1.HealthzResponse.status:type_name -> v1.ServiceStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apiserver_v1_healthz_proto_init() }
func file_apiserver_v1_healthz_proto_init() {
	if File_apiserver_v1_healthz_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apiserver_v1_healthz_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*HealthzResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apiserver_v1_healthz_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_healthz_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_healthz_proto_depIdxs,
		EnumInfos:         file_apiserver_v1_healthz_proto_enumTypes,
		MessageInfos:      file_apiserver_v1_healthz_proto_msgTypes,
	}.Build()
	File_apiserver_v1_healthz_proto = out.File
	file_apiserver_v1_healthz_proto_rawDesc = nil
	file_apiserver_v1_healthz_proto_goTypes = nil
	file_apiserver_v1_healthz_proto_depIdxs = nil
}
